services:
  backend:
    image: registry.gitlab.com/taucher2003-group/devmarkt-backend:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - default.env
      - .env
    environment:
      MICRONAUT_ENVIRONMENTS: qa
      DEVMARKT_POSTGRES_HOST: postgres
      DEVMARKT_POSTGRES_DATABASE: postgres
      DEVMARKT_POSTGRES_USER: postgres
      DEVMARKT_POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres

  bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - default.env
      - .env
