services:
  backend:
    image: registry.gitlab.com/taucher2003-group/devmarkt-backend:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - local-services
      - devmarkt-dev

networks:
  local-services:
    external: true
  devmarkt-dev:
    external: true